(feat): Adds support of two functions from the task1
Kadochnikov-Daniil/formal-lang-course pull request #1
Opened 2024-09-11 17:19 UTC by Kadochnikov-Daniil

Adds get_graph_info, which return nodes, edges and labels of the given graph.
Adds create_two_cycle_graph, which creates graph with two cycles with given labels and amount of nodes for both cycles and saves it to the given path
Adds tests for both functions
[×] Сделать fork данного репозитория.
[×] Добавить ссылку на ваш fork в [таблицу](https://docs.google.com/spreadsheets/d/1X7Hx6IyltD_NyTTphyzbN74Ag-G_LDzUu4OGcHoI8tg/edit?usp=sharing).
[×] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в таблицу)
[×] Реализовать модуль, предоставляющий перечисленные ниже возможности. Для работы с графами использовать [cfpq-data](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#graphs). Данный модуль в дальнейшем будет расширяться. Функции, которые необходимо реализовать:
[×] По имени графа вернуть количество вершин, рёбер и перечислить различные метки, встречающиеся на рёбрах. Для получения графа по имени использовать [эту функцию](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/tutorial.html#load-graph).
[×] По количеству вершин в циклах и именам меток строить [граф из двух циклов](https://formallanguageconstrainedpathquerying.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.generators.labeled_two_cycles_graph.html#cfpq_data.graphs.generators.labeled_two_cycles_graph) и сохранять его в указанный файл в формате DOT (использовать pydot).
[×] Добавить необходимые тесты.

2024-09-12 08:25 UTC, vadyushkins requested changes

2024-09-12 08:25 UTC, vadyushkins commented on tests/test_create_two_cycle_graph.py
> +    graph = networkx.nx_pydot.from_pydot(pydot_graph)
У вас неправильно протестирована функциональность сохранения файла в dot. Должны быть готовые файлы dot, которые вы открываете и сравниваете с тем, что делает ваша функция

2024-09-12 09:09 UTC, Kadochnikov-Daniil commented on tests/test_create_two_cycle_graph.py
> +    graph = networkx.nx_pydot.from_pydot(pydot_graph)
Понял, просто не хотел привязываться к конкретным тестовым фалам, так как изначально вообще думал сделать рандомную генерацию чисел для "nodes_left" и "nodes_right". Да и вообще показалось, что нет смысла в таком тесте, потому что файл, с которым сравниваем, - такой же сгенерированный файл этой же функции, просто сохраненный, как эталон. Но раз надо так, то надо.

2024-09-17 13:19 UTC, vadyushkins commented on tests/test_create_two_cycle_graph.py
> +    graph = networkx.nx_pydot.from_pydot(pydot_graph)
Вы так детерминируете ожидания, отвязываясь от функции, поведение которой может измениться в будущем

2024-09-17 13:19 UTC, vadyushkins approved these changes

2024-09-17 13:21 UTC, merged