(feat): Adds two functions from the task2
Kadochnikov-Daniil/formal-lang-course pull request #2
Opened 2024-09-16 12:56 UTC by Kadochnikov-Daniil

2024-09-17 13:25 UTC, vadyushkins requested changes

2024-09-17 13:25 UTC, vadyushkins commented on project/converter.py
> +    dfa = Regex("abc|d").to_epsilon_nfa().to_deterministic()
```suggestion
    dfa = Regex(regex).to_epsilon_nfa().to_deterministic()
```

2024-09-17 13:25 UTC, vadyushkins commented on tests/test_graph_to_nfa.py
> +    assert len(nfa.final_states) == 5
1. Используйте параметризацию pytest, чтобы на один тест был один тесткейс
2. Протестируйте крайние случаи. Если граф пустой. Если вершины не из графа. Подумайте какие еще.

2024-09-23 09:33 UTC, Kadochnikov-Daniil commented on project/converter.py
> +    dfa = Regex("abc|d").to_epsilon_nfa().to_deterministic()
Исправил опечатку.

2024-09-23 09:34 UTC, Kadochnikov-Daniil commented on tests/test_graph_to_nfa.py
> +    assert len(nfa.final_states) == 5
Если правильно понял, то оба пункта сделал.

2024-09-24 14:45 UTC, vadyushkins approved these changes
ОК, но дальше затащите CI из апстрима, чтобы нам с вами с тестами жить было легче

2024-09-30 06:23 UTC, merged